name: LatentUQ
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.2
  - pandas=1.3.3
  - matplotlib=3.4.3
  - scikit-learn=0.24.2
  - pytorch=1.10.0
  - torchvision=0.11.1
  - cudatoolkit=11.1  # If you are using a GPU, adjust the version as needed
  - pip