data_dir: "data"
dataset: "poisson"
model: "DeepONet"
batch_size: 100
channels: 1
sigma_y: 0.01
gmm_dim: 10
gmm_components: 2
sampler: "ula"
likelihood: "gauss"
num_steps: 50
step_size: !!float 5e-2
epochs: 1000
lr_GMM: !!float 1e-3
lr_G: !!float 1e-2
plot: False
testing: False